# Generated by Django 4.2.8 on 2024-02-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
